apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["curl",  "https://google.com"]
      restartPolicy: Never
  backoffLimit: 1